version: '3.8'

services:
  booki-db:
    image: postgres:15
    restart: always
    container_name: booki-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - booki-db:/var/lib/postgresql/data

volumes:
  booki-db: